### PR TITLE
player_monoids support

### PR DESCRIPTION
**Pull request by tacotexmex**
Well that was easy.

### CODE REVIEW

**Comment by octacian** [comment]
I assume you've tested and this works?

**Comment by tacotexmex** [comment]
Yup! It's a soft dependency, so it falls back to the old method if player_monoids isn't available.

**Comment by octacian** [comment]
261db79690dbdbdf8d6e013dcf52d3fca95f4a92

**Comment by tacotexmex** [comment]
Nice!

**Pull request merged**
