### PR TITLE
Bug causing monoids not to be used removed

### PR DESCRIPTION
**Pull request by tacotexmex**
Sorry! :D

### CODE REVIEW

**Comment by octacian** [comment]
hmm, I meant to push a commit to fix this myself earlier, however, I was having an issue where the `player_monoids.speed` table was `nil`. Any thoughts?

**Comment by tacotexmex** [comment]
I haven't had that problem. Is that perhaps if mod isn't present? The modpath checK should take care of that if so.

**Comment by octacian** [comment]
OK, I'll do a bit more testing. Will probably push my own commit to fix this, but keep the PR open in the meantime.

**Comment by tacotexmex** [comment]
Sure thing.

**Comment by octacian** [comment]
Just reviewed the code, and I don't think this will work. You define a local variable inside an if statement, therefore it is accessible only within said conditional. The best way to solve this is to define a variable that is equal to `minetest.get_modpath("player_monoids")` and check that way. You're welcome to update this PR, but I will otherwise do it myself within the next week after some other things are implemented.

**Edit:** Also, on this particular PR, conflicts need to be resolved.

**Comment by tacotexmex** [comment]
I’ve since written my own sprint mod from scratch, [hbSprint](https://forum.minetest.net/viewtopic.php?f=9&t=18069&p=312296#p282981), and implemented it there.

**Pull request closed without merging**
